// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MParseFront
{
    using MParse.Core.GrammarElements;
    using MParse.Core;
    using System.Linq;
    using System;
    
    
    #line 1 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ParserTemplate : ParserCodeGenBase
    {
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 5 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_codeNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using System;\r\n    using System.Collections.Generic;\r\n\r\n    public class" +
                    " Parser \r\n    {\r\n        public ");
            
            #line 12 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write(" Parse(IEnumerable<");
            
            #line 12 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TerminalBaseClassName));
            
            #line default
            #line hidden
            this.Write("> tokens)\r\n        {\r\n\t\t\tif (!tokens.MoveNext())\r\n                throw new Argum" +
                    "entException(\"Cannot access tokens.\", \"tokens\");\r\n\r\n            var stateStack =" +
                    " new Stack<int>();\r\n            var parseStack = new Stack<");
            
            #line 18 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write(@">();
            stateStack.Push(0);

            while(true)
            {
                var t = tokens.Current;
                var result = t.Action(stateStack, parseStack);
                if ((result == ActionResult.Accept))
                {
                    break;
                }
                if (result == ActionResult.ShiftContinue)
                {
                    tokens.MoveNext();
                    continue;
                }
                if (result == ActionResult.ReduceContinue)
                {
                    var reducer = ((");
            
            #line 36 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.ReductionInterfaceName));
            
            #line default
            #line hidden
            this.Write(@")(parseStack.Peek()));
                    reducer.Goto(stateStack);
                    continue;
                }
                if (result == ActionResult.Error)
                {
                    throw new Exception(""Parsing Failed."");
                }
            }
            return (");
            
            #line 45 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write(")parseStack.Pop();\r\n        }\r\n    }\r\n\r\n    public interface IParseTreeVisitor\r\n " +
                    "   {\r\n");
            
            #line 51 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

foreach(var symbol in _symbols)
{
if(symbol is Terminal)
{

            
            #line default
            #line hidden
            this.Write("        void Visit_");
            
            #line 57 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((Terminal)symbol).Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 57 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((Terminal)symbol).Name));
            
            #line default
            #line hidden
            this.Write(" terminal);\r\n");
            
            #line 58 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}
else
{
foreach(var prod in _productions.Where(x => x.Head == symbol))
{
var className = GetClassName(prod);

            
            #line default
            #line hidden
            this.Write("        void Visit_");
            
            #line 66 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 66 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" nonTerminal);\r\n");
            
            #line 67 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}
}
}

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public abstract class ");
            
            #line 74 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private Guid _nodeId;\r\n\r\n        public ");
            
            #line 78 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            _nodeId = Guid.NewGuid();\r\n        }\r\n\r\n        public" +
                    " virtual void AcceptVisitor(IParseTreeVisitor visitor)\r\n        {\r\n            /" +
                    "/No default implementation\r\n        }\r\n    }\r\n    \r\n    public abstract class ");
            
            #line 89 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TerminalBaseClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 89 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private string _text;\r\n        \r\n        protected ");
            
            #line 93 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TerminalBaseClassName));
            
            #line default
            #line hidden
            this.Write(@"(string text)
        {
            _text = text;
        }
        
        public string Text
        {
            get
            {
                return _text;
            }
        }
        
        public abstract ActionResult Action(Stack<int> stateStack, Stack<");
            
            #line 106 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write(@"> parseStack);
        
        public override string ToString()
        {
            return _text;
        }
    }

    public enum ActionResult
    {
        Error,
        Accept,
        ShiftContinue,
        ReduceContinue,
    }

    public interface ");
            
            #line 122 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.ReductionInterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        void Goto(Stack<int> stateStack);\r\n    }\r\n\r\n");
            
            #line 127 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

foreach (var symbol in _symbols)
{
if (symbol is Terminal)
{

            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 133 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(symbol.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 133 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TerminalBaseClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 135 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(symbol.Name));
            
            #line default
            #line hidden
            this.Write("(string text) : base(text)\r\n        {\r\n        }\r\n\r\n        public override Actio" +
                    "nResult Action(Stack<int> stateStack, Stack<");
            
            #line 139 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("> parseStack)\r\n        {\r\n            int currentState = stateStack.Peek();\r\n");
            
            #line 142 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

foreach (var state in _table.States)
{
var action = _table[state, symbol];

            
            #line default
            #line hidden
            this.Write("            if(currentState == ");
            
            #line 147 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.StateId));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n");
            
            #line 149 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

if (action.Action == ParserAction.Shift)
{

            
            #line default
            #line hidden
            this.Write("                stateStack.Push(");
            
            #line 153 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.NextState.StateId));
            
            #line default
            #line hidden
            this.Write(");\r\n                parseStack.Push(this);\r\n                return ActionResult.S" +
                    "hiftContinue;\r\n");
            
            #line 156 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            
            #line 159 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

if (action.Action == ParserAction.Reduce)
{

            
            #line default
            #line hidden
            this.Write("                parseStack.Push(");
            
            #line 163 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassName(action.ReduceByProduction)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 163 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.ReduceByMethodName));
            
            #line default
            #line hidden
            this.Write("(parseStack));\r\n");
            
            #line 164 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

for (int i = 0; i < action.ReduceByProduction.Length; i++)
{

            
            #line default
            #line hidden
            this.Write("                stateStack.Pop();\r\n");
            
            #line 169 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("                return ActionResult.ReduceContinue;\r\n");
            
            #line 173 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            
            #line 176 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

if (action.Action == ParserAction.Accept)
{

            
            #line default
            #line hidden
            this.Write("                return ActionResult.Accept;\r\n");
            
            #line 181 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            
            #line 184 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

if (action.Action == ParserAction.Error)
{

            
            #line default
            #line hidden
            this.Write("                return ActionResult.Error;\r\n");
            
            #line 189 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("            }\r\n");
            
            #line 193 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n\r\n");
            
            #line 199 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}
else
{

            
            #line default
            #line hidden
            this.Write("\tpublic abstract class ");
            
            #line 204 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(symbol.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 204 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 204 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.ReductionInterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic void Goto(Stack<int> stateStack)\r\n\t\t{\r\n\t\t\tint currentState = state" +
                    "Stack.Peek();\r\n");
            
            #line 209 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

foreach (var state in _table.States)
{
var action = _table[state, symbol];
if (action.Action == ParserAction.Goto)
{

            
            #line default
            #line hidden
            this.Write("\t\t\tif(currentState == ");
            
            #line 216 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.StateId));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t{\r\n\t\t\t\tstateStack.Push(");
            
            #line 218 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.NextState.StateId));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\treturn;\r\n\t\t\t}\r\n");
            
            #line 221 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}
}

            
            #line default
            #line hidden
            this.Write("\t\t\tthrow new Exception(\"Unexpected GOTO operation.\");\r\n\t\t}\r\n\t}\r\n\r\n");
            
            #line 229 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}
}

            
            #line default
            #line hidden
            
            #line 233 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

foreach(var symbol in _symbols.Where(x => x is NonTerminal))
foreach(var prod in _productions.Where(x => x.Head == symbol ))
{
var className = GetClassName(prod);

            
            #line default
            #line hidden
            this.Write("\tpublic partial class ");
            
            #line 239 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 239 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prod.Head));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 241 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

for(int i = 0; i < prod.Length; i++)
{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 245 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prod[i].Name));
            
            #line default
            #line hidden
            this.Write(" T");
            
            #line 245 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n");
            
            #line 246 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 250 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(IList<");
            
            #line 250 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("> nodes)\r\n\t\t{\r\n\t\t\tif(nodes.Length != ");
            
            #line 252 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prod.Length));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t{\r\n\t\t\t\tthrow new ArgumentException(\"The list of nodes given is of the wrong" +
                    " length.\", \"nodes\");\r\n\t\t\t}\r\n");
            
            #line 256 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

for(int i = 0; i < prod.Length; i++)
{

            
            #line default
            #line hidden
            this.Write("\t\t\tT");
            
            #line 260 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 260 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prod[i].Name));
            
            #line default
            #line hidden
            this.Write(")nodes[");
            
            #line 260 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 261 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic static ");
            
            #line 266 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 266 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.ReduceByMethodName));
            
            #line default
            #line hidden
            this.Write("(Stack<");
            
            #line 266 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("> parseStack)\r\n\t\t{\r\n\t\t\t//reverse the nodes because they are popped off in the inv" +
                    "erted order.\r\n\t\t\tvar nodes = new ");
            
            #line 269 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Constants.TreeNode));
            
            #line default
            #line hidden
            this.Write("[]\r\n\t\t\t{\r\n");
            
            #line 271 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

for(int i = 0; i < prod.Length; i++)
{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tparseStack.Pop(),\r\n");
            
            #line 276 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\t\t\t}.Reverse().ToArray();\r\n\t\t}\r\n\t}\r\n\r\n");
            
            #line 283 "C:\Projects\MParse\MParseFront\ParserTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("} //End Namespace\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
